#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRLeft,         sensorI2CCustom)
#pragma config(Sensor, S3,     IRRight,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontHigh,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLow,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    scoop,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    AutoLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    AutoRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

const float firstBasketInches = 18;
const float secondBasketInches = 8;
const float thirdBasketInches = 14;
const float inchesToRotations = 9.42;
const float turnDistanceLeft = 15;
const float turnDistanceRight = 13;
const float turnToLine = 29;
const float forwardSpeed = 50.0;
const float turnSpeed = 40;
string forward = "forward";
string backwards = "backwards";
string rightDirection = "right";
string leftDirection = "left";

float distanceToEncoderValue(float distance){
	return (distance/inchesToRotations) * 360;
}

float convertInches(float inches){
	return (1440/9.42) * inches;
}

/*
 *Method that moves the robot towards the rung to place the ring
 *parameters
 *inches - the number of inches to move the robot
**/
void scoreBlock(){

	servoTarget[AutoLeft] = 0;
	servoTarget[AutoRight] = 0;

	wait1Msec(500);

	servoTarget[AutoLeft] = 150;
	servoTarget[AutoRight] = 150;

	wait1Msec(750);
}

void moveRobot(float distance, float speed, string direction){
	nMotorEncoder[right] = 0;
	nMotorEncoder[left] = 0;

	nMotorEncoderTarget[right] = convertInches(distance);
	nMotorEncoderTarget[left] = convertInches(distance);

	if(forward == direction){
		motor[right] = speed;
		motor[left] = speed;
	}
	else if(backwards == direction){
		motor[right] = -speed;
		motor[left] = -speed;
	}
	else if(rightDirection == direction){
		motor[right] = -speed;
		motor[left] = speed;
	}
	else if(leftDirection == direction){
		motor[right] = speed;
		motor[left] = -speed;
	}

	while(nMotorRunState[right] != runStateIdle || nMotorRunState[left] != runStateIdle){
	}
		motor[right] = 0;
		motor[left] = 0;
}

void parkRobot(){
		moveRobot(turnDistanceLeft, turnSpeed, leftDirection);
		moveRobot(turnToLine, forwardSpeed, forward);
		moveRobot(turnDistanceRight, turnSpeed, rightDirection);
		moveRobot(turnToLine, forwardSpeed, forward);
}

task main()
{
	//initializeRobot();
	waitForStart();
	motor[frontLow] = 100;
	wait1Msec(250);
	motor[frontLow] = 0;
	//wait10Msec(100);

	tHTIRS2DSPMode _mode = DSP_1200;
	int direction = HTIRS2readDCDir(IRLeft);

	moveRobot(firstBasketInches, forwardSpeed, forward);
	wait1Msec(25);

	if(HTIRS2readDCDir(IRLeft) == 5){
		scoreBlock();
		moveRobot(firstBasketInches - 1, forwardSpeed, backwards);
		parkRobot();
	}
	else{
		moveRobot(secondBasketInches, forwardSpeed, forward);
		wait1Msec(25);
		if(HTIRS2readACDir(IRLeft) == 5){
			scoreBlock();
			moveRobot(firstBasketInches + secondBasketInches - 1, forwardSpeed, backwards);
			parkRobot();
		}
		else{
			moveRobot(thirdBasketInches, forwardSpeed, forward);
			wait1Msec(25);
			if(HTIRS2readACDir(IRLeft) == 5){
				scoreBlock();
				moveRobot(firstBasketInches + secondBasketInches + thirdBasketInches- 1, forwardSpeed, backwards);
				parkRobot();
			}
			else{
				moveRobot(secondBasketInches, forwardSpeed, forward);
				scoreBlock();
				moveRobot(firstBasketInches + secondBasketInches + thirdBasketInches + secondBasketInches - 1, forwardSpeed, backwards);
				parkRobot();
			}
		}
	}
}
