#pragma config(Sensor, S4,     irSeeker,       sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"

const float startFirst = 0;
const float firstSecond = 0;
const float secondThird = 0;
const float thirdFourth = 0;
const float outerToTurn = 0;
const float turnDistance = 0;
const float turnToLine = 0;
const float lineToPark = 0;
const int firstMarker = 5;
const int secondMarker = 7;
const int thirdMarker = 9;

void moveRobot(float distance, bool direction){
}

void parkingMovement(int half){
	if(half == 1){
		moveRobot(turnDistance, true); //Need to change moveRobot to handle a turn
	}
	else{
		moveRobot(turnDistance, false); //Need to change moveRobot to handle a turn
	}

	moveRobot(turnToLine, true);

	if(half ==1){
		moveRobot(turnDistance, true);
	}
	else{
		moveRobot(turnDistance, false);
	}

	moveRobot(lineToPark, true);
}

void depositBlock(){
}

void differentScoringMovement(){
	int time = 0;
	motor[motorB] = 50;
	motor[motorC] = 50;
	
	while(HTIRS2readDCDir(irSeeker) != 5){
		time++;
	}
	
	motor[motorB] = 0;
	motor[motorC] = 0;
	
	//make 45 degree turn and go forward
	motor[motorB] = -50;
	motor[motorC] = -50;
	
	int timer = 0;
	
	while(timer < time){
		timer++;
	}
	
	motor[motorB] = 0;
	motor[motorC] = 0;
}

int convertDistance(int distance){
	return 1;
}

void scoringMovement(){
	int sensorValue = HTIRS2readDCDir(irSeeker);

	//First basket move
	moveRobot(startFirst, true);

	if(sensorValue == firstMarker){
		depositBlock();
		moveRobot(outerToTurn, false);
		parkingMovement(0);
		return;
	}

	//Second basket move
	moveRobot(firstSecond, true);

	if(sensorValue == secondMarker){
		depositBlock();
		moveRobot(firstSecond, false);
		moveRobot(outerToTurn, false);
		parkingMovement(0);
		return;
	}

	//Third basket move
	moveRobot(secondThird, true);

	if(sensorValue == thirdMarker){
		depositBlock();
		moveRobot(thirdFourth, true);
		moveRobot(outerToTurn, true);
		parkingMovement(1);
		return;
	}

	//Fourth basket move
	moveRobot(thirdFourth, true);
	depositBlock();
	moveRobot(outerToTurn, true);
	parkingMovement(1);
}

task main()
{
	tHTIRS2DSPMode _mode = DSP_1200;
	while(true){
		int sensorDirection = HTIRS2readDCDir(irSeeker);
		nxtDisplayBigStringAt(0, 31,"%d",sensorDirection);
	}
	//scoringMovement();
}
