#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     IRLeft,         sensorI2CCustom)
#pragma config(Sensor, S3,     IRRight,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     frontHigh,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLow,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    scoop,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    AutoLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    AutoRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                  Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an Tetrix robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"

const float FirstBasketInches = 18;
const float SecondBasketInches = 8;
const float ThirdBasketInches = 13;
const float FourthBasketInches = 8;
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                      initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
 	tHTIRS2DSPMode _mode = DSP_1200;
  return;
}

/*
 *Method used to convert rotations into a value usable by the encoders
 *parameters:
 *rotations - the number of rotations to convert
**/
float convertRotations(float rotations){
	return 1440 * rotations;
}

/*
 *Method used to convert inches into a value usable by the encoders
 *parameters:
 *rotations - the number of inches to convert
**/
float convertInches(float inches){
	return (1440/9.42) * inches;
}

/*
 *Method used to set the arm before moving the robot
**/

void FirstMove(float inches){

	nMotorEncoder[right] = 0;
	nMotorEncoder[left] = 0;

	wait10Msec(5);

	nMotorEncoderTarget[right] = convertInches(inches);
	nMotorEncoderTarget[left] = convertInches(inches);

	motor[right] = 70;
	motor[left] = 70;

	while(nMotorRunState[right] != runStateIdle || nMotorRunState[left] != runStateIdle){
	}
}

/*
 *Method used to make the turn towards any of the rungs
 *parameters
 *rotations - the number of rotations for the encoders
**/
void SecondMove(float inches){
		nMotorEncoder[right] = 0;
	nMotorEncoder[left] = 0;

	wait10Msec(5);

	nMotorEncoderTarget[right] = convertInches(inches);
	nMotorEncoderTarget[left] = convertInches(inches);

	motor[right] = 70;
	motor[left] = 70;

	while(nMotorRunState[right] != runStateIdle || nMotorRunState[left] != runStateIdle){
	}
}

void ThirdMove(float inches){
		nMotorEncoder[right] = 0;
	nMotorEncoder[left] = 0;

	wait10Msec(5);

	nMotorEncoderTarget[right] = convertInches(inches);
	nMotorEncoderTarget[left] = convertInches(inches);

	motor[right] = 70;
	motor[left] = 70;

	while(nMotorRunState[right] != runStateIdle || nMotorRunState[left] != runStateIdle){
	}
}

void FourthMove(float inches){
		nMotorEncoder[right] = 0;
	nMotorEncoder[left] = 0;

	wait10Msec(5);

	nMotorEncoderTarget[right] = convertInches(inches);
	nMotorEncoderTarget[left] = convertInches(inches);

	motor[right] = 70;
	motor[left] = 70;

	while(nMotorRunState[right] != runStateIdle || nMotorRunState[left] != runStateIdle){
	}
}

/*
 *Method that moves the robot towards the rung to place the ring
 *parameters
 *inches - the number of inches to move the robot
**/
void ScoreBlock(){

	servoTarget[AutoLeft] = 0;
	servoTarget[AutoRight] = 0;

	wait1Msec(1000);

	servoTarget[AutoLeft] = 150;
	servoTarget[AutoRight] = 150;



	wait1Msec(500);
}

/*
 *Method that backs away from the rack and turns the robot towards the ring holders
 *
**/



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                          Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

/*	while(true){
		sensorDirection = HTIRS2readDCDir(IRLeft);
		nxtDisplayBigStringAt(0, 31, "%d", sensorDirection);
	}
}*/
	initializeRobot();
	//waitForStart();

  int _dirAC = 0;

  wait1Msec(200);

  int sensorDirection = HTIRS2readDCDir(IRLeft);

  FirstMove(FirstBasketInches);

  wait1Msec(200);

  if(sensorDirection == 5){
  	ScoreBlock();
	}
	else{

		SecondMove(SecondBasketInches);
		wait1Msec(500);
		sensorDirection = HTIRS2readDCDir(IRLeft);
		if(sensorDirection == 5 ){
			ScoreBlock();
		}

		else{}

		/*ThirdMove(ThirdBasketInches);
		wait1Msec(500);
		sensorDirection = HTIRS2readDCDir(IRLeft);
		if(sensorDirection < 6){
			ScoreBlock();
		}

		else{}

		FourthMove(FourthBasketInches);
		wait1Msec(500);
		sensorDirection = HTIRS2readDCDir(IRLeft);
		if(sensorDirection < 6){
			ScoreBlock();
		}
	*/

}}
