#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     front,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rightSpeedDefault = 3;
int leftSpeedDefault = -3;
int rightSpeed = rightSpeedDefault;
int leftSpeed = leftSpeedDefault;

task ButtonTask()
{
 nSchedulePriority	 = kHighPriority;

  //
  // Update count of times each button is pushed. If using this program as a template, replace these
  // statements with your own custom action.
  //
  switch (nNxtButtonPressed)
  {
  	case kExitButton:

			break;

  	case kLeftButton:
		  motor[front] = leftSpeed;
		  leftSpeed = leftSpeed - leftSpeed;
			break;

		case kRightButton:
		  motor[front] = rightSpeed;
		  rightSpeed = rightSpeed + rightSpeed;
			break;

		case kEnterButton:
		motor[front] = 0;
		leftSpeed = leftSpeedDefault;
		rightSpeed = rightSpeedDefault;

	}
}

task main()
{
	//
	// "Hi-jack" buttons for user program control.
	//
	// Note: program cannot be terminated if we hijack the 'exit' button. So there has to be an escape sequence
	//       that will return buttons to system control!
	//
	nNxtExitClicks    = 2;
	nNxtButtonTask    = ButtonTask;

	nxtDisplayTextLine(2, "  < to Decrease");
  nxtDisplayTextLine(3, "  > to Increase");
  nxtDisplayTextLine(4, "  Enter to Stop");
  nxtDisplayTextLine(5, "  ExitX2 to Exit");
	//
	// Do nothing. Just keep waiting
	//
	while (true)
	{
		//
		// Some dummy code to do some work.
		//
	  wait1Msec(50);
  }
	return;
}
