#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     frontHigh,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLow,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    scoop,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Define class variables
const float MAX_JOYSTICK = 128.0;
const float MOTOR_POWER = 50.0;

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{

  // Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

//Basic function for moving the robot

	int getMotorOutput(int joystickValue){

    int directionValue = joystickValue / abs(joystickValue);
  	float ratio = (joystickValue * joystickValue) / (MAX_JOYSTICK * MAX_JOYSTICK);
		return (ratio * (MOTOR_POWER * MOTOR_POWER)) * directionValue;
	}

  void moveLift() {

    if(joy1Btn(6)){
			motor[frontLow] = 100;
		}
		else{
			motor[frontLow] = 0;
		}

		if(joy1Btn(5)){
			motor[frontLow] = -100;
		}
		else{
			motor[frontLow] = 0;
			}
	  if(joy1Btn(8)){
			motor[frontHigh] = 100;
		}
		else{
			motor[frontHigh] = 0;
		}

		if(joy1Btn(7)){
				motor[frontHigh] = -100;
		}
		else{
			motor[frontHigh] = 0;
		}
	}

  void moveBucket() {

    if(joy1Btn(3)){
			servoTarget[scoop] = ServoValue(scoop) + 5;
		}
		else if(joy1Btn(1)){
			servoTarget[scoop] = ServoValue(scoop) - 5;
		}
	}

  void moveFlag() {

    if(joy1Btn(2)){
			motor[flag] = 07;
		}
		else if(joy1Btn(4)){
			motor[flag] = 100;
		}
		else{
			motor[flag] = 0;
	}
}
  void drive()  {

    motor[right] = getMotorOutput(joystick.joy1_y2);
		motor[left] = getMotorOutput(joystick.joy1_y1);

}

task main()
{
  bFloatDuringInactiveMotorPWM = false;
  // wait for start of tele-op phase
	//tor[right] = 100;

  //basic instructions for robot
  while (true){
  	getJoystickSettings(joystick);
		drive();
		moveLift();
		moveBucket();
		moveFlag();
	}
}
